-- Deploy donm:0014-slugify to pg
-- requires: 0013-trim-subprefecture-address

BEGIN;

ALTER TABLE region ADD column slug TEXT;

UPDATE region SET slug = 'butanta' WHERE id = '649';
UPDATE region SET slug = 'carrao' WHERE id = '581';
UPDATE region SET slug = 'guaianases' WHERE id = '580';
UPDATE region SET slug = 'itaim-paulista' WHERE id = '615';
UPDATE region SET slug = 'itaquera' WHERE id = '607';
UPDATE region SET slug = 'jose-bonifacio' WHERE id = '597';
UPDATE region SET slug = 'lajeado' WHERE id = '598';
UPDATE region SET slug = 'morumbi' WHERE id = '579';
UPDATE region SET slug = 'sao-miguel' WHERE id = '593';
UPDATE region SET slug = 'campo-limpo' WHERE id = '638';
UPDATE region SET slug = 'cidade-tiradentes' WHERE id = '627';
UPDATE region SET slug = 'pedreira' WHERE id = '642';
UPDATE region SET slug = 'ponte-rasa' WHERE id = '641';
UPDATE region SET slug = 'vila-sonia' WHERE id = '635';
UPDATE region SET slug = 'campo-belo' WHERE id = '652';
UPDATE region SET slug = 'campo-grande' WHERE id = '646';
UPDATE region SET slug = 'jardim-paulista' WHERE id = '636';
UPDATE region SET slug = 'marsilac' WHERE id = '639';
UPDATE region SET slug = 'penha' WHERE id = '645';
UPDATE region SET slug = 'sao-lucas' WHERE id = '647';
UPDATE region SET slug = 'se' WHERE id = '644';
UPDATE region SET slug = 'tatuape' WHERE id = '637';
UPDATE region SET slug = 'vila-curuca' WHERE id = '651';
UPDATE region SET slug = 'vila-formosa' WHERE id = '643';
UPDATE region SET slug = 'vila-guilherme' WHERE id = '653';
UPDATE region SET slug = 'vila-maria' WHERE id = '640';
UPDATE region SET slug = 'parque-do-carmo' WHERE id = '672';
UPDATE region SET slug = 'agua-rasa' WHERE id = '616';
UPDATE region SET slug = 'anhanguera' WHERE id = '595';
UPDATE region SET slug = 'aricanduva' WHERE id = '663';
UPDATE region SET slug = 'barra-funda' WHERE id = '671';
UPDATE region SET slug = 'cambuci' WHERE id = '586';
UPDATE region SET slug = 'cangaiba' WHERE id = '670';
UPDATE region SET slug = 'cidade-ademar' WHERE id = '660';
UPDATE region SET slug = 'consolacao' WHERE id = '668';
UPDATE region SET slug = 'itaim-bibi' WHERE id = '585';
UPDATE region SET slug = 'jardim-angela' WHERE id = '583';
UPDATE region SET slug = 'limao' WHERE id = '674';
UPDATE region SET slug = 'rio-pequeno' WHERE id = '669';
UPDATE region SET slug = 'sao-rafael' WHERE id = '587';
UPDATE region SET slug = 'saude' WHERE id = '584';
UPDATE region SET slug = 'tremembe' WHERE id = '650';
UPDATE region SET slug = 'vila-andrade' WHERE id = '582';
UPDATE region SET slug = 'alto-de-pinheiros' WHERE id = '599';
UPDATE region SET slug = 'belem' WHERE id = '603';
UPDATE region SET slug = 'cachoeirinha' WHERE id = '589';
UPDATE region SET slug = 'cidade-dutra' WHERE id = '604';
UPDATE region SET slug = 'cidade-lider' WHERE id = '605';
UPDATE region SET slug = 'jacana' WHERE id = '588';
UPDATE region SET slug = 'jaguara' WHERE id = '606';
UPDATE region SET slug = 'jaragua' WHERE id = '601';
UPDATE region SET slug = 'pirituba' WHERE id = '592';
UPDATE region SET slug = 'sao-domingos' WHERE id = '596';
UPDATE region SET slug = 'sao-mateus' WHERE id = '600';
UPDATE region SET slug = 'vila-jacui' WHERE id = '602';
UPDATE region SET slug = 'vila-leopoldina' WHERE id = '591';
UPDATE region SET slug = 'vila-mariana' WHERE id = '594';
UPDATE region SET slug = 'vila-prudente' WHERE id = '590';
UPDATE region SET slug = 'freguesia-do-o' WHERE id = '621';
UPDATE region SET slug = 'artur-alvim' WHERE id = '624';
UPDATE region SET slug = 'bras' WHERE id = '618';
UPDATE region SET slug = 'brasilandia' WHERE id = '632';
UPDATE region SET slug = 'ermelino-matarazzo' WHERE id = '654';
UPDATE region SET slug = 'grajau' WHERE id = '609';
UPDATE region SET slug = 'ipiranga' WHERE id = '622';
UPDATE region SET slug = 'jabaquara' WHERE id = '610';
UPDATE region SET slug = 'jardim-helena' WHERE id = '631';
UPDATE region SET slug = 'jardim-sao-luis' WHERE id = '620';
UPDATE region SET slug = 'liberdade' WHERE id = '629';
UPDATE region SET slug = 'mandaqui' WHERE id = '608';
UPDATE region SET slug = 'perdizes' WHERE id = '625';
UPDATE region SET slug = 'perus' WHERE id = '623';
UPDATE region SET slug = 'pinheiros' WHERE id = '614';
UPDATE region SET slug = 'raposo-tavares' WHERE id = '628';
UPDATE region SET slug = 'republica' WHERE id = '611';
UPDATE region SET slug = 'sacoma' WHERE id = '630';
UPDATE region SET slug = 'santana' WHERE id = '612';
UPDATE region SET slug = 'tucuruvi' WHERE id = '613';
UPDATE region SET slug = 'vila-matilde' WHERE id = '617';
UPDATE region SET slug = 'vila-medeiros' WHERE id = '626';
UPDATE region SET slug = 'casa-verde' WHERE id = '656';
UPDATE region SET slug = 'cursino' WHERE id = '664';
UPDATE region SET slug = 'iguatemi' WHERE id = '659';
UPDATE region SET slug = 'lapa' WHERE id = '662';
UPDATE region SET slug = 'moema' WHERE id = '661';
UPDATE region SET slug = 'parelheiros' WHERE id = '666';
UPDATE region SET slug = 'santo-amaro' WHERE id = '665';
UPDATE region SET slug = 'sapopemba' WHERE id = '658';
UPDATE region SET slug = 'bela-vista' WHERE id = '648';
UPDATE region SET slug = 'bom-retiro' WHERE id = '619';
UPDATE region SET slug = 'capao-redondo' WHERE id = '657';
UPDATE region SET slug = 'jaguare' WHERE id = '673';
UPDATE region SET slug = 'mooca' WHERE id = '655';
UPDATE region SET slug = 'pari' WHERE id = '633';
UPDATE region SET slug = 'santa-cecilia' WHERE id = '667';
UPDATE region SET slug = 'socorro' WHERE id = '634';

ALTER TABLE region ALTER COLUMN slug SET NOT NULL;

ALTER TABLE goal ADD column slug TEXT;

UPDATE goal SET slug = 'aumentar-a-cobertura-da-atencao-basica-a-saude-para-70-na-ci' WHERE id = '1';
UPDATE goal SET slug = 'reduzir-em-5-7-obitos-prematuros-em-100-000-residentes-a-tax' WHERE id = '2';
UPDATE goal SET slug = 'transformar-sao-paulo-em-cidade-amiga-do-idoso-obtendo-o-sel' WHERE id = '7';
UPDATE goal SET slug = 'reduzir-o-indice-de-mortes-no-transito-para-valor-igual-ou-i' WHERE id = '25';
UPDATE goal SET slug = 'certificar-75-630-dos-estabelecimentos-municipais-de-saude-c' WHERE id = '3';
UPDATE goal SET slug = 'reduzir-o-tempo-medio-de-espera-para-exames-prioritarios-par' WHERE id = '4';
UPDATE goal SET slug = 'diminuir-a-taxa-de-mortalidade-infantil-em-5-0-6-obitos-em-1' WHERE id = '5';
UPDATE goal SET slug = 'criar-2-000-novas-vagas-para-atendimento-humanizado-em-saude' WHERE id = '6';
UPDATE goal SET slug = 'assegurar-acolhimento-para-no-minimo-90-da-populacao-em-situ' WHERE id = '9';
UPDATE goal SET slug = 'gerar-oportunidades-de-inclusao-produtiva-por-meio-das-acoes' WHERE id = '38';
UPDATE goal SET slug = 'garantir-100-de-encaminhamentos-das-denuncias-recebidas-cont' WHERE id = '21';
UPDATE goal SET slug = 'garantir-15-000-vagas-de-atividades-para-idosos-com-objetivo' WHERE id = '8';
UPDATE goal SET slug = 'contribuir-para-a-reducao-dos-crimes-de-oportunidade-em-10-4' WHERE id = '10';
UPDATE goal SET slug = 'ampliar-em-20-a-taxa-de-atividade-fisica-na-cidade-de-sao-pa' WHERE id = '11';
UPDATE goal SET slug = 'expandir-em-30-85-5-mil-as-matriculas-em-creche-na-rede-muni' WHERE id = '12';
UPDATE goal SET slug = 'atingir-ideb-de-6-5-nos-anos-iniciais-do-ensino-fundamental' WHERE id = '13';
UPDATE goal SET slug = 'atingir-ideb-de-5-8-nos-anos-finais-do-ensino-fundamental' WHERE id = '14';
UPDATE goal SET slug = '95-dos-alunos-com-no-minimo-nivel-de-proficiencia-basico-na' WHERE id = '15';
UPDATE goal SET slug = 'alcancar-95-dos-alunos-alfabetizados-ao-final-do-segundo-ano' WHERE id = '16';
UPDATE goal SET slug = '100-46-dos-ceus-transformados-em-polos-de-inovacao-em-tecnol' WHERE id = '17';
UPDATE goal SET slug = 'todo-aluno-e-todo-professor-em-escolas-municipais-de-ensino' WHERE id = '18';
UPDATE goal SET slug = 'aumentar-em-15-504-535-o-publico-total-frequentador-dos-equi' WHERE id = '19';
UPDATE goal SET slug = 'aumentar-em-15-142-820-o-publico-frequentador-do-sistema-mun' WHERE id = '20';
UPDATE goal SET slug = 'alcancar-150-empresas-que-facam-a-adesao-voluntaria-ao-selo' WHERE id = '22';
UPDATE goal SET slug = 'plantar-200-mil-arvores-no-municipio-com-prioridade-para-as' WHERE id = '23';
UPDATE goal SET slug = 'reduzir-em-500-mil-toneladas-o-total-dos-residuos-enviados-a' WHERE id = '24';
UPDATE goal SET slug = 'aumentar-em-7-o-uso-do-transporte-publico-em-sao-paulo-ate-2' WHERE id = '27';
UPDATE goal SET slug = 'aumentar-em-10-a-participacao-dos-modos-ativos-de-deslocamen' WHERE id = '26';
UPDATE goal SET slug = 'reduzir-em-15-156-649-ton-a-emissao-de-co2-em-50-37-ton-a-em' WHERE id = '28';
UPDATE goal SET slug = '25-mil-unidades-habitacionais-entregues-para-atendimento-via' WHERE id = '29';
UPDATE goal SET slug = '210-mil-familias-beneficiadas-por-procedimentos-de-regulariz' WHERE id = '30';
UPDATE goal SET slug = '27-500-familias-beneficiadas-com-urbanizacao-integrada-em-as' WHERE id = '31';
UPDATE goal SET slug = 'reduzir-em-15-3-4-km2-as-areas-inundaveis-da-cidade' WHERE id = '32';
UPDATE goal SET slug = 'implantar-um-novo-padrao-de-uso-racional-da-agua-e-eficienci' WHERE id = '33';
UPDATE goal SET slug = 'melhorar-as-condicoes-de-acessibilidade-em-200-equipamentos' WHERE id = '34';
UPDATE goal SET slug = 'valorizacao-do-centro-com-intervencoes-urbanisticas-visando' WHERE id = '35';
UPDATE goal SET slug = 'reduzir-o-tempo-medio-de-emissao-dos-alvaras-de-aprovacao-e' WHERE id = '36';
UPDATE goal SET slug = 'melhorar-a-classificacao-de-sao-paulo-no-mapa-de-inseguranca' WHERE id = '37';
UPDATE goal SET slug = 'aumentar-em-10-1-353-entre-2017-e-2019-a-quantidade-de-empre' WHERE id = '39';
UPDATE goal SET slug = 'reduzir-o-tempo-para-abertura-e-formalizacao-de-empresas-de' WHERE id = '40';
UPDATE goal SET slug = 'implantar-o-padrao-poupatempo-em-todas-as-32-regionais' WHERE id = '41';
UPDATE goal SET slug = 'duplicar-os-pontos-de-wifi-livre-criando-mais-120-pontos-na' WHERE id = '42';
UPDATE goal SET slug = 'garantir-que-100-dos-novos-processos-sejam-eletronicos-reduz' WHERE id = '43';
UPDATE goal SET slug = 'viabilizar-r-5-bilhoes-de-impacto-financeiro-para-a-prefeitu' WHERE id = '44';
UPDATE goal SET slug = 'aumentar-em-10-r-1-17-bilhao-o-valor-acumulado-de-investimen' WHERE id = '47';
UPDATE goal SET slug = 'aumentar-em-20-r-224-58-no-periodo-de-2017-a-2020-o-investim' WHERE id = '45';
UPDATE goal SET slug = 'reduzir-20-das-despesas-operacionais-r-96-6-milhoes-em-relac' WHERE id = '46';
UPDATE goal SET slug = 'ampliar-em-10-r-989-milhoes-a-arrecadacao-da-divida-ativa-do' WHERE id = '48';
UPDATE goal SET slug = 'garantir-que-100-dos-dados-publicados-pela-prefeitura-esteja' WHERE id = '49';
UPDATE goal SET slug = 'aumentar-em-50-2-65-o-indice-de-integridade-da-prefeitura-de' WHERE id = '50';
UPDATE goal SET slug = 'duplicar-as-visualizacoes-34-5-milhoes-do-portal-da-prefeitu' WHERE id = '51';
UPDATE goal SET slug = 'reduzir-de-90-para-70-dias-o-tempo-medio-de-atendimento-dos' WHERE id = '52';
UPDATE goal SET slug = 'garantir-acoes-concentradas-de-zeladoria-urbana-em-200-eixos' WHERE id = '53';

ALTER TABLE goal ALTER COLUMN slug SET NOT NULL;

ALTER TABLE project ADD column slug TEXT;

UPDATE project SET slug = 'amplia-saude' WHERE id = '1';
UPDATE project SET slug = 'viver-mais-e-melhor' WHERE id = '2';
UPDATE project SET slug = 'vida-urgente' WHERE id = '3';
UPDATE project SET slug = 'saude-digital' WHERE id = '4';
UPDATE project SET slug = 'qualifica-saude' WHERE id = '5';
UPDATE project SET slug = 'acelerasaude-corujao-da-saude' WHERE id = '6';
UPDATE project SET slug = 'viva-a-crianca' WHERE id = '7';
UPDATE project SET slug = 'redencao' WHERE id = '8';
UPDATE project SET slug = 'trabalho-novo' WHERE id = '9';
UPDATE project SET slug = 'direitos-humanos-na-cidade' WHERE id = '10';
UPDATE project SET slug = 'cidade-amiga-do-idoso' WHERE id = '11';
UPDATE project SET slug = 'cadmais-sp' WHERE id = '12';
UPDATE project SET slug = 'longevidade' WHERE id = '13';
UPDATE project SET slug = 'universidade-aberta-da-pessoa-idosa' WHERE id = '14';
UPDATE project SET slug = 'espacos-vida' WHERE id = '15';
UPDATE project SET slug = 'seguranca-inteligente' WHERE id = '16';
UPDATE project SET slug = 'cidade-segura' WHERE id = '17';
UPDATE project SET slug = 'sao-paulo-cidade-ativa' WHERE id = '18';
UPDATE project SET slug = 'nossa-creche' WHERE id = '19';
UPDATE project SET slug = 'alfabetizacao' WHERE id = '20';
UPDATE project SET slug = 'apoio-pedagogico' WHERE id = '21';
UPDATE project SET slug = 'avaliacao-externa' WHERE id = '22';
UPDATE project SET slug = 'curriculo-da-cidade-de-sao-paulo' WHERE id = '23';
UPDATE project SET slug = 'acesso-e-permanencia' WHERE id = '24';
UPDATE project SET slug = 'sao-paulo-educadora' WHERE id = '25';
UPDATE project SET slug = 'ceu-21' WHERE id = '26';
UPDATE project SET slug = 'escola-digital' WHERE id = '27';
UPDATE project SET slug = 'cultura-em-parceria' WHERE id = '28';
UPDATE project SET slug = 'cultura-sampa' WHERE id = '29';
UPDATE project SET slug = 'biblioteca-viva' WHERE id = '30';
UPDATE project SET slug = 'centros-de-cidadania' WHERE id = '31';
UPDATE project SET slug = 'selo-de-direitos-humanos-e-diversidade' WHERE id = '32';
UPDATE project SET slug = 'sampa-verde' WHERE id = '33';
UPDATE project SET slug = 'recicla-sampa' WHERE id = '34';
UPDATE project SET slug = 'pedestre-seguro' WHERE id = '35';
UPDATE project SET slug = 'transito-seguro' WHERE id = '36';
UPDATE project SET slug = 'ciclomobilidade' WHERE id = '37';
UPDATE project SET slug = 'mutirao-mario-covas-e-calcada-nova' WHERE id = '38';
UPDATE project SET slug = 'mobilidade-inteligente' WHERE id = '39';
UPDATE project SET slug = 'cidade-conectada' WHERE id = '40';
UPDATE project SET slug = 'transporte-meu' WHERE id = '41';
UPDATE project SET slug = 'casa-da-familia' WHERE id = '42';
UPDATE project SET slug = 'construcao-ou-reforma-de-unidades-habitacionais-para-locacao' WHERE id = '43';
UPDATE project SET slug = 'programa-de-regularizacao-fundiaria' WHERE id = '44';
UPDATE project SET slug = 'urbanizacao-integrada-em-assentamentos-precarios' WHERE id = '45';
UPDATE project SET slug = 'cidade-resiliente' WHERE id = '46';
UPDATE project SET slug = 'controle-de-cheias' WHERE id = '47';
UPDATE project SET slug = 'sustentabilidade-das-edificacoes' WHERE id = '48';
UPDATE project SET slug = 'cidade-acessivel' WHERE id = '49';
UPDATE project SET slug = 'centro-lindo' WHERE id = '50';
UPDATE project SET slug = 'licenca-rapida' WHERE id = '51';
UPDATE project SET slug = 'alimentando-sp' WHERE id = '52';
UPDATE project SET slug = 'trabalho-emprego-e-renda' WHERE id = '53';
UPDATE project SET slug = 'sao-paulo-criativa' WHERE id = '54';
UPDATE project SET slug = 'empreenda-facil' WHERE id = '55';
UPDATE project SET slug = 'descomplica-sp' WHERE id = '56';
UPDATE project SET slug = 'wifi-sp' WHERE id = '57';
UPDATE project SET slug = 'sao-paulo-digital' WHERE id = '58';
UPDATE project SET slug = 'plano-municipal-de-desestatizacao' WHERE id = '59';
UPDATE project SET slug = 'sao-paulo-cidade-do-mundo' WHERE id = '60';
UPDATE project SET slug = 'combate-a-sonegacao-fiscal' WHERE id = '61';
UPDATE project SET slug = 'orcamento-sustentavel' WHERE id = '62';
UPDATE project SET slug = 'gestores-da-economia' WHERE id = '63';
UPDATE project SET slug = 'sao-paulo-sem-divida-ativa' WHERE id = '64';
UPDATE project SET slug = 'sao-paulo-aberta' WHERE id = '65';
UPDATE project SET slug = 'acessibilidade-digital' WHERE id = '66';
UPDATE project SET slug = 'sao-paulo-integra-e-transparente' WHERE id = '67';
UPDATE project SET slug = 'comunica-sp' WHERE id = '68';
UPDATE project SET slug = 'sp-156-canal-rapido-e-direto' WHERE id = '69';
UPDATE project SET slug = 'asfalto-novo' WHERE id = '70';
UPDATE project SET slug = 'cidade-linda' WHERE id = '71';

ALTER TABLE project ALTER COLUMN slug SET NOT NULL;


ALTER TABLE topic ADD column slug TEXT;

UPDATE topic SET slug = 'desenvolvimento-humano' WHERE id = '1';
UPDATE topic SET slug = 'desenvolvimento-social' WHERE id = '2';
UPDATE topic SET slug = 'desenvolvimento-urbano-e-meio-ambiente' WHERE id = '3';
UPDATE topic SET slug = 'desenvolvimento-institucional' WHERE id = '4';
UPDATE topic SET slug = 'desenvolvimento-economico-e-gestao' WHERE id = '5';

ALTER TABLE topic ALTER COLUMN slug SET NOT NULL;

COMMIT;
