-- Deploy donm:0017-aciton-line-indicator-achievement to pg
-- requires: 0016-goal-indicator

BEGIN;

ALTER TABLE action_line ADD COLUMN indicator_description TEXT ;
ALTER TABLE action_line ADD COLUMN achievement TEXT ;

UPDATE action_line SET indicator_description = 'Nº de novas equipes de ESF implantadas' WHERE id = 1 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de novos profissionais médicos na Atenção Básica à Saúde contratados' WHERE id = 1 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de novos NASF implantados' WHERE id = 1 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de novas equipes de saúde bucal implantadas' WHERE id = 1 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Taxa de perda primária média de consultas médicas em UBS' WHERE id = 1 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Percentual de profissionais da Atenção Básica capacitados por Prefeitura Regional' WHERE id = 1 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Taxa de desabastecimento médio das unidades de saúde de itens de responsabilidade municipal' WHERE id = 1 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de ações intersetoriais de promoção à saúde realizadas por ano' WHERE id = 1 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Nº de novas UBS entregues' WHERE id = 1 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Nº UBS readequadas e/ou reformadas' WHERE id = 1 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Cobertura de exames de Papanicolau da população alvo' WHERE id = 1 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS com monitoramento da abordagem mínima e básica do Programa Nacional de Controle do Tabagismo' WHERE id = 2 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS que oferecem Práticas Integrativas e Complementares (PIC) em Saúde' WHERE id = 2 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de novos nutricionistas contratados' WHERE id = 2 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de Coordenadorias Regionais de Saúde com Plano de Rastreamento das DCNT implantado' WHERE id = 2 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de Coordenadorias Regionais de Saúde com Plano de Atenção Integral à Saúde do Homem implantado' WHERE id = 2 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de Coordenadorias Regionais de Saúde com Plano de educação permanente para o enfrentamento das DCNT implantado' WHERE id = 2 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Proporção de óbitos nas internações por ICC e seus agravos nos estabelecimentos de gestão municipal' WHERE id = 2 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Proporção de óbitos nas internações por AVE nos estabelecimentos de gestão municipal' WHERE id = 2 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Proporção de óbitos nas internações por IAM nos estabelecimentos de gestão municipal' WHERE id = 2 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Nº de novos de centros de reabilitação implantados' WHERE id = 2 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Nº de serviços de reabilitação revitalizados' WHERE id = 2 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'Nº de órteses, próteses e meios auxiliares de locomoção (OPM) fornecidos nos serviços de reabilitação' WHERE id = 2 AND subid = 12 ;
UPDATE action_line SET indicator_description = 'Percentual de atendimento de demandas de baixa prioridade' WHERE id = 3 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de atendimento das demandas de alta prioridade em até 12 minutos' WHERE id = 3 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de atendimento de demandas de saúde mental' WHERE id = 3 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de Veículos de Intervenção Rápida (VIR) em uso' WHERE id = 3 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de novas bases do SAMU integradas implantadas' WHERE id = 3 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Percentual de viaturas em uso 24h' WHERE id = 3 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Percentual de unidades de urgência e emergência capacitadas nas linhas de cuidado da RUE' WHERE id = 3 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Percentual de unidades de acolhimento de urgência e emergência com classificação de risco implantada' WHERE id = 3 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Índice Diário de Médicos Médio' WHERE id = 3 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Nº de serviços de urgência e emergência implantados' WHERE id = 3 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'Nº de serviços de urgência e emergência reformados/readequados' WHERE id = 3 AND subid = 12 ;
UPDATE action_line SET indicator_description = 'Nº de hospitais entregues' WHERE id = 3 AND subid = 13 ;
UPDATE action_line SET indicator_description = 'Percentual de hospitais da Rede Municipal com prontuário eletrônico implantado' WHERE id = 4 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de ambulatórios de especialidades da rede municipal com prontuário eletrônico implantado.' WHERE id = 4 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS da Rede Municipal com prontuário eletrônico implantado' WHERE id = 4 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS cobertas por teleconsultores' WHERE id = 4 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Percentual de estabelecimentos com multiplicador capacitado no Modelo de Gestão da Qualidade, Humanização e Segurança do Paciente da Secretaria Municipal da Saúde' WHERE id = 5 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de estabelecimentos com planos de ação em andamento' WHERE id = 5 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de estabelecimentos avaliados para certificação no Modelo de Gestão da Qualidade, Humanização e Segurança do Paciente da SMS' WHERE id = 5 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Prêmio Anual Municipal de Gestão da Qualidade, Humanização e Segurança do Paciente realizado anualmente' WHERE id = 5 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de protocolos de acesso a exames prioritários revisados publicados' WHERE id = 6 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS e AE com médicos capacitados' WHERE id = 6 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS e AE com regulação local instalada' WHERE id = 6 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Taxa média de absenteísmo dos pacientes em exames' WHERE id = 6 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Taxa média de perda primária da agenda de exames' WHERE id = 6 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de vagas de exames disponibilizadas' WHERE id = 6 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de implantes subdérmicos utilizados' WHERE id = 7 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de gestantes captadas precocemente com 1ª consulta realizada até 12 semanas (inclusive) em UBS.' WHERE id = 7 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de equipes de neonatologia das oito maternidades municipais capacitadas para a atenção ao recém-nascido' WHERE id = 7 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de dispositivos intrauterinos utilizados' WHERE id = 7 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de recém-nascidos SUS agendados em 1º consulta (médico e enfermeiro) ou em visita domiciliar em até 7 dias de vida' WHERE id = 7 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de maternidades sob gestão municipal com grupo de alta qualificada implantado' WHERE id = 7 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Percentual de equipes de ESF capacitadas para o aleitamento materno e alimentação saudável' WHERE id = 7 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS com equipes ESF capacitadas que realizaram ações de aleitamento e/ou alimentação complementar' WHERE id = 7 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Taxa de parto normal nas maternidades sob gestão municipal' WHERE id = 7 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Percentual de equipes de ESF capacitadas para as doenças prevalentes no período neonatal' WHERE id = 7 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Nº de obstetrizes contratadas' WHERE id = 7 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'Percentual de equipes capacitadas' WHERE id = 8 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Percentual de equipes capacitadas' WHERE id = 8 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Número de novas equipes implantadas' WHERE id = 8 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Número de novas vagas criadas em CAPS AD' WHERE id = 8 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Número de novas vagas criadas' WHERE id = 8 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Número de novas vagas criadas em SRT' WHERE id = 8 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'Número de novas vagas criadas em UA' WHERE id = 8 AND subid = 12 ;
UPDATE action_line SET indicator_description = 'Número de novos leitos hospitalares de desintoxicação disponibilizados' WHERE id = 8 AND subid = 13 ;
UPDATE action_line SET indicator_description = 'Número de novas vagas criadas em CAPS III' WHERE id = 8 AND subid = 15 ;
UPDATE action_line SET indicator_description = 'Campanhas realizadas' WHERE id = 8 AND subid = 18 ;
UPDATE action_line SET indicator_description = 'Nº de Vagas Negociadas' WHERE id = 9 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de Usuários capacitados' WHERE id = 9 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de Empresas capacitadas' WHERE id = 9 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual de setores de recursos humanos acompanhados' WHERE id = 9 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Equipes constituídas de acordo com cronograma (indicador de monitoramento)' WHERE id = 10 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Número de balcões de cidadania implantados' WHERE id = 10 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Índice de satisfação do usuário do balcão de cidadania' WHERE id = 10 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Percentual de UBS com equipe de referência em saúde da pessoa idosa' WHERE id = 11 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de idosos com AMPI-AB realizada' WHERE id = 11 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de hospitais municipais com equipes de gestão de alta' WHERE id = 11 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'N° de novas URSI implantadas' WHERE id = 11 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de URSI com adequação de infraestrutura e recursos humanos' WHERE id = 11 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Nº de ILPI implantadas' WHERE id = 11 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Número de Centros-Dia para Idososimplantados' WHERE id = 11 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Percentual de equipamentos socioassistenciais para idosos de média e alta complexidade de SMADS (ILPI - Grau II e III, CDI e CAE) com equipes de saúde' WHERE id = 11 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'N° de novas equipes PAI' WHERE id = 11 AND subid = 12 ;
UPDATE action_line SET indicator_description = 'N° idosos com 80 anos ou mais incluídos nos serviços de monitoramento' WHERE id = 11 AND subid = 13 ;
UPDATE action_line SET indicator_description = 'Nº de CECCO com oficinais intergeracionais realizadas por ano' WHERE id = 11 AND subid = 14 ;
UPDATE action_line SET indicator_description = 'Nº de sistemas de cadastramento em operação' WHERE id = 12 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Taxa de inserção no CADÚnico dos usuários da rede de SCFV' WHERE id = 12 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Taxa de atualização cadastral do CADÚnico' WHERE id = 12 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Taxa de inserção no CADÚnico dos usuários dos serviços para idosos no âmbito da Proteção Social Especial' WHERE id = 12 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Percentual de profissionais capacitados' WHERE id = 13 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Diagnóstico efetuado' WHERE id = 13 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de Prefeituras Regionais com CCINTER' WHERE id = 13 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de partipantes concluintes' WHERE id = 14 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº total de UAPIs' WHERE id = 14 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de Matriculados' WHERE id = 14 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de Espaços Vida implantados' WHERE id = 15 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de Centros de Acolhida aprimorados' WHERE id = 15 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de unidades de acolhimento para População em Situação de Rua avaliadas' WHERE id = 15 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de Espaços Vida com capacitação' WHERE id = 15 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Percentual de pessoas acolhidas em Repúblicas' WHERE id = 15 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de CTAs Implantados' WHERE id = 15 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de inspetorias regionais cujos membros participem em CONSEGs' WHERE id = 16 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de câmeras de videomonitoramento integradas' WHERE id = 16 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de agentes de segurança urbana capacitados para o uso do sistema “Compstat Paulistano”' WHERE id = 16 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de Guardas civis contratados' WHERE id = 17 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de Guardas civis realocados para ações externas' WHERE id = 17 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de Guardas afastados capacitados para o desempenho de atividades administrativas' WHERE id = 17 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de Guardas afastados do trabalho por razões médicas e psicológicas' WHERE id = 17 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de armas substituídas' WHERE id = 17 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de motocicletas adquiridas' WHERE id = 17 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de equipamentos reformados' WHERE id = 18 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de inscritos nos programas' WHERE id = 18 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual de crianças e adolescentes inscritos no Programa Clube Escola' WHERE id = 18 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Realização da Virada Esportiva com atividades em todas as regiões' WHERE id = 18 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Realização dos Jogos da Cidade reestruturados' WHERE id = 18 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de Ruas de Lazer implantadas' WHERE id = 18 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Crescimento anual de matrículas em creches' WHERE id = 19 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Número de matrículas de crianças de famílias em situação de pobreza' WHERE id = 19 AND subid = 4 ;
UPDATE action_line SET indicator_description = '% Professores do Ciclo de Alfabetização e Recuperação Paralela concluintes de ações de formação sobre alfabetização' WHERE id = 20 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Taxa de resposta da Provinha São Paulo' WHERE id = 20 AND subid = 2 ;
UPDATE action_line SET indicator_description = '% de turmas do 1º ano do EF com a presença de um estagiário para apoio ao professor' WHERE id = 20 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Porcentagem de professores dos anos finais do ensino fundamental concluintes de ações de formação específica' WHERE id = 21 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Porcentagem de equipes pedagógicas das DREs com formação sobre organização de plano de ação e acompanhamento de aprendizagem' WHERE id = 21 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Frequência mediana dos alunos do EF matriculados na Sala de Recursos Multifuncionais' WHERE id = 21 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Acompanhamento de unidades educacionais realizado pelas equipes do NAAPA nas DREs' WHERE id = 21 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Média da taxa de resposta da Prova São Paulo' WHERE id = 22 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Média da taxa de resposta da Prova Semestral' WHERE id = 22 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Taxa de resposta da Provinha São Paulo' WHERE id = 22 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Número de concluintes de cursos sobre análise de dados de avaliações como subsídio ao planejamento pedagógico' WHERE id = 22 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Taxa de resposta do simulado do ENEM' WHERE id = 22 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Porcentagem de supervisores, diretores e CPs da RME concluintes de ações de formação para a implementação do Currículo da Cidade de São Paulo' WHERE id = 23 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Porcentagem de POEIs do EF formados para trabalhar a partir do pensamento computacional (letramento digital, tecnologia da informação e comunicação e linguagem de programação)' WHERE id = 23 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Porcentagem de crianças e adolescentes que estavam fora da escola matriculados na RME após identificação' WHERE id = 24 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Porcentagem de turmas monitoradas por sistema permanente de alerta de infrequência escolar' WHERE id = 24 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Número de profissionais participantes de ações de formação voltadas ao enfrentamento do abandono e outras formas de exclusão educacional' WHERE id = 24 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Quantidade de EMEFs de CEUs com turmas de Educação Integral em tempo integral (no mínimo 7 horas diárias e/ou 35 semanais)' WHERE id = 25 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Quantidade de EMEFs com turmas de educação integral em tempo integral (no mínimo 7 horas diárias e/ou 35 semanais)' WHERE id = 25 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Quantidade de alunos do ensino fundamental em Educação Integral em tempo integral (no mínimo 7 horas diárias e/ou 35 semanais)' WHERE id = 25 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Porcentagem de POEIs formados' WHERE id = 26 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Quantidade de EMEFs com LEDs implantados' WHERE id = 26 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Quantidade de CEUs com LEDs implantados' WHERE id = 26 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Porcentagem de unidades com LEDs praticando o currículo e plano pedagógico' WHERE id = 26 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Porcentagem de EMEFs com dispositivos de rede existentes (firewall e switches) e servidores locais revisados e reconfigurados' WHERE id = 27 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Porcentagem de EMEFs com dispositivos de compressão de dados adquiridos, configurados e instalados' WHERE id = 27 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Porcentagem de EMEFs com novos links de comunicação de dados ativados' WHERE id = 27 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Porcentagem de EMEFs com solução de comunicação de dados sem fio (WIFI) ativadas' WHERE id = 27 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Porcentagem de EMEFs com servidores (equipamento) para distribuição de conteúdos pedagógicos instalados' WHERE id = 27 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Número de equipamentos administrados pelo novo modelo de gestão. ' WHERE id = 28 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Número de parcerias estabelecidas para cessão de espaços públicos ociosos para fins e atividades culturais.' WHERE id = 28 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de Casas de Cultura requalificadas' WHERE id = 29 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Variação percentual no número de eventos do Circuito Municipal de Cultura realizados nas Casas de Cultura' WHERE id = 29 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de artistas que realizaram atividade sem Casas de Cultura fora de sua região de origem' WHERE id = 29 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual de equipamentos culturais com acessibilidade arquitetônica.' WHERE id = 29 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Percentual de distritos que possuem salas de cinema.' WHERE id = 29 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Percentual de equipamentos culturais com rede Wifi disponível.' WHERE id = 29 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Percentual de bibliotecas (SMB) abertas aos domingos' WHERE id = 30 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Variação percentual do número de atividades regulares realizadas na programação do SMB' WHERE id = 30 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de profissionais capacitados para trabalhar no programa Biblioteca Viva' WHERE id = 30 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual de bibliotecas com WiFi disponível' WHERE id = 30 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de bibliotecas com nova estratégia expositiva implementada' WHERE id = 30 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Percentual de bibliotecas que realizaram o mapeamento do acervo' WHERE id = 30 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Variação percentual no número de livros novos relacionados a literatura no acervo geral do SMB' WHERE id = 30 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Número de “Pontos de Leitura instalados”' WHERE id = 30 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Percentual de bibliotecas com requalificação estrutural. ' WHERE id = 30 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Número de equipes formadas' WHERE id = 31 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Número de oficinas realizadas' WHERE id = 31 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Número de pessoas trans atendidas pelo Programa Transcidadania' WHERE id = 31 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Número de Centros de Promoção da Igualdade Racial entregues' WHERE id = 31 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Número de atendimento realizados pelos Centros' WHERE id = 31 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Número de empresas que aderiram ao modelo de políticas afirmativas na força de trabalho' WHERE id = 32 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de eventos realizados' WHERE id = 32 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de concursos realizados' WHERE id = 32 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Percentual de parques com parcerias Implementada' WHERE id = 33 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Áreas identificadas para realização de plantios.' WHERE id = 33 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de projetos realizados' WHERE id = 33 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de árvores plantadas por SVMA  cadastradas e georreferenciadas' WHERE id = 33 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Área verde plantadas com arvores de pequeno porte' WHERE id = 33 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Percentual de resíduos de feiras e podas de árvores  reaproveitados' WHERE id = 34 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Quantidade de adesões das escolas que possuem área disponível para compostagem.' WHERE id = 34 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Catadores e cooperados qualificados tecnicamente.' WHERE id = 34 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Volume da coleta seletiva em relação ao valor de 2016' WHERE id = 34 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Percentual de edifícios públicos com coleta Seletiva' WHERE id = 34 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de parcerias/acordos firmados' WHERE id = 34 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Nº de vias conectadas a estações ou terminais de transporte público' WHERE id = 35 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de manuais publicados' WHERE id = 35 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de projetos de redesenho urbano Implantados' WHERE id = 35 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de rotas com acessibilidade implantadas' WHERE id = 35 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de corredores de ônibus que passaram por intervenções de segurança para o pedestre' WHERE id = 35 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de vias com ações implementadas de operação e sinalização com atenção intensificada ao pedestre' WHERE id = 35 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'No de condutores cadastrados durante o período de vigência do programa' WHERE id = 36 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'No de alunos alcançados pelas ações' WHERE id = 36 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'No de munícipes alcançados pelas ações' WHERE id = 36 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'No de operadores do sistema de transporte público impactados pelo programa' WHERE id = 36 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Pesquisas realizadas' WHERE id = 37 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de startups incubadas' WHERE id = 37 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de beneficiários ao ano' WHERE id = 38 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de estações implantadas' WHERE id = 38 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Índice de conectividade da rede cicloviária' WHERE id = 38 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Área de passeios requalificados' WHERE id = 39 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Área de passeios requalificados' WHERE id = 39 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Extensão de corredores de ônibus entregues (construídos e em operação)' WHERE id = 40 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de terminais de ônibus entregues (construídos e em operação)' WHERE id = 40 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de veículos novos' WHERE id = 41 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de veículos com ar condicionado, tomadas USB e WiFi' WHERE id = 41 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual da frota com acessibilidade universal' WHERE id = 41 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de novos lugares no período pico da manhã' WHERE id = 41 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais contratadas para construção ou reforma' WHERE id = 42 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais contratadas para construção ou reforma' WHERE id = 42 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais contratadas para construção ou reforma' WHERE id = 42 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais contratadas para construção ou reforma' WHERE id = 42 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais contratadas para construção ou reforma' WHERE id = 42 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais contratadas ' WHERE id = 42 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais contratadas' WHERE id = 42 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de Unidades Habitacionais para construção ou reforma que receberam Habite-se (PARHIS)' WHERE id = 42 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Unidades habitacionais contratadas para construção ou reforma para locação social.' WHERE id = 43 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de famílias beneficiadas com títulos de garantia de direito de posse entregues' WHERE id = 44 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de famílias beneficiadas com títulos de garantia de direito de propriedade entregues' WHERE id = 44 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de famílias beneficiadas com o registro do parcelamento em áreas particulares' WHERE id = 44 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de famílias beneficiadas com o registro do parcelamento em áreas públicas' WHERE id = 44 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de famílias beneficiadas com a regularização municipal do parcelamento em áreas particulares' WHERE id = 44 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de famílias beneficiadas com a regularização municipal do parcelamento em áreas públicas' WHERE id = 44 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de famílias beneficiadas com o licenciamento ambiental em áreas de mananciais (APRMs)' WHERE id = 44 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Famílias beneficiadas com obras de urbanização de assentamentos precários em andamento.' WHERE id = 45 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Famílias beneficiadas com obras de urbanização de assentamentos precários em mananciais em andamento.' WHERE id = 45 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de áreas de risco geológico com mapeamento atualizado' WHERE id = 46 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de NUDECs fortalecidos' WHERE id = 46 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de NUDECs criados' WHERE id = 46 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de escolas com o Programa Saúde, Proteção e Defesa Civil na Escola e o Grupo Defesa Civil Escolar implantado' WHERE id = 46 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de planos de contingência elaborados, priorizando as áreas de riscos alto e muito alto' WHERE id = 46 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Programa de Controle do uso do solo implantado no Sistema Municipal de Defesa Civil' WHERE id = 46 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Planos de Bacia elaborados' WHERE id = 47 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de córregos prioritários limpos' WHERE id = 47 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual de galerias prioritárias Desobstruídas' WHERE id = 47 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Percentual de reservatórios de retenção desassoreados' WHERE id = 47 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Aricanduva' WHERE id = 47 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Ipiranga' WHERE id = 47 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Uberaba' WHERE id = 47 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Cordeiro' WHERE id = 47 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Zavuvus' WHERE id = 47 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Ponte Baixa' WHERE id = 47 AND subid = 12 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Perus' WHERE id = 47 AND subid = 13 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Tremembé' WHERE id = 47 AND subid = 14 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - Paciência' WHERE id = 47 AND subid = 15 ;
UPDATE action_line SET indicator_description = 'Entrega de funcionalidades - PRA' WHERE id = 47 AND subid = 16 ;
UPDATE action_line SET indicator_description = 'Implantação de intervenção em parceria com o DAEE e outros agentes' WHERE id = 47 AND subid = 18 ;
UPDATE action_line SET indicator_description = 'Índice de adequação de projetos' WHERE id = 48 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de vistorias realizadas' WHERE id = 49 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de publicações lançadas' WHERE id = 49 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de agentes públicos capacitados' WHERE id = 49 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de projetos arquitetônicos analisados' WHERE id = 49 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de vistorias realizadas' WHERE id = 49 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de Selos de acessibilidade concedidos' WHERE id = 49 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Área pública requalificada' WHERE id = 50 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Calçadas e calçadão requalificados' WHERE id = 50 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Área pública requalificada' WHERE id = 50 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Área pública requalificada' WHERE id = 50 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Toneladas de alimentos captados' WHERE id = 52 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Número de produtores atendidos anualmente' WHERE id = 52 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Horas de serviços prestados pela Patrulha Agroecológica Mecanizada' WHERE id = 52 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Número de pessoas atendidas' WHERE id = 52 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Número de regiões com ofertas de alimentos' WHERE id = 52 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Número de hortas atendidas' WHERE id = 52 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Número de trabalhadores colocados via SINE em relação ao número total de trabalhadores admitidos segundo o CAGED' WHERE id = 53 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Beneficiários do POT e BT colocados no mercado de trabalho (IMO, MEI, ME, EPP ou cooperado)' WHERE id = 53 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Número palestras/eventos temáticos realizados, coordenados ou incentivados pela PMSP sobre empreendedorismo e microempreendedor individual' WHERE id = 54 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Número de beneficiários concluintes da capacitação inicial em economia criativa' WHERE id = 54 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Número de instituições aderentes ao Programa de Cultura Empreendedora' WHERE id = 54 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Prefeituras regionais com rede lógica renovada' WHERE id = 55 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Prefeituras regionais com link de acesso à internet ampliado para 16 Mb' WHERE id = 55 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Prefeituras regionais com parque de microcomputadores da Supervisão de Uso do Solo e Licenciamento (SUSL) renovado' WHERE id = 55 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Número de seminários realizados' WHERE id = 55 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Estruturas físicas com serviços de atendimento ao empreendedor operando, devidamente formalizadas' WHERE id = 55 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Número de atendimento a empreendedores realizados' WHERE id = 55 AND subid = 10 ;
UPDATE action_line SET indicator_description = 'Soma das novas unidades implantadas' WHERE id = 56 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Soma dos novos postos de trabalho capacitados' WHERE id = 56 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Número de serviços no Guia/Número total de serviços atendidos nas unidades presenciais' WHERE id = 56 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'índice de velocidade por usuário' WHERE id = 57 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Soma das novas pesquisas de satisfação realizadas no período' WHERE id = 57 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Soma dos novos pontos de WiFi implantados' WHERE id = 57 AND subid = 3 ;
UPDATE action_line SET indicator_description = '% de processos mapeados para migração' WHERE id = 58 AND subid = 1 ;
UPDATE action_line SET indicator_description = '% do público-alvo capacitado' WHERE id = 58 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Número de projetos contratados' WHERE id = 59 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Número de projetos com modelagem concluída' WHERE id = 59 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Número de projetos lançados a mercado' WHERE id = 59 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Número de projetos com contrato assinado' WHERE id = 59 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de missões realizadas.' WHERE id = 60 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Nº de ações de projeção da cidade realizadas.' WHERE id = 60 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de eventos internacionais realizados' WHERE id = 60 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de ações de cooperação internacional realizadas' WHERE id = 60 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Nº de ações de promoção local, nacional e internacional realizadas' WHERE id = 60 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Quantidade de servidores capacitados' WHERE id = 61 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de PPPs lançadas com avaliação de garantias públicas (100%).' WHERE id = 62 AND subid = 3 ;
UPDATE action_line SET indicator_description = 'Percentual de constituição das garantias nas PPPs avaliadas (100%).' WHERE id = 62 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Montante de recursos levantados por meio de securitização de créditos parcelados (R$500 mi)' WHERE id = 62 AND subid = 5 ;
UPDATE action_line SET indicator_description = '% de Secretarias e Prefeituras Regionais com Gestores da Economia nomeados' WHERE id = 63 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Despesas com Bens e Suprimentos Comuns' WHERE id = 63 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Despesas com Locação de Imóveis' WHERE id = 63 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Percentual de Certidões de Dívida Ativa Protestadas' WHERE id = 64 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de reuniões realizadas' WHERE id = 65 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de relatórios publicados' WHERE id = 65 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de oficinas realizadas' WHERE id = 65 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de dignósticos setorializados' WHERE id = 65 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Finalização do ciclo' WHERE id = 65 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Nº de gestores e servidores capacitados' WHERE id = 65 AND subid = 11 ;
UPDATE action_line SET indicator_description = 'Nº de agentes da sociedade civilcapacitados' WHERE id = 65 AND subid = 12 ;
UPDATE action_line SET indicator_description = 'Nº de sistemas com atualização automatizada dos dados' WHERE id = 65 AND subid = 13 ;
UPDATE action_line SET indicator_description = 'Nº de eventos realizados' WHERE id = 66 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de avaliações programadas realizadas' WHERE id = 66 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Percentual de parcerias programadas firmadas' WHERE id = 66 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Percentual de selos emitidos para o setor público e/ou privado' WHERE id = 66 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Nº de Programas de Integridade implementados' WHERE id = 67 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Nº de servidores que operam o sistema de transparência passiva (SIC) formados.' WHERE id = 67 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Nº de servidores e funcionários de cada órgão da Administração Direta Municipal para atuação no controle interno formados' WHERE id = 67 AND subid = 4 ;
UPDATE action_line SET indicator_description = 'Nº de servidores que atuam como pontos focais das demandas de ouvidoria formados' WHERE id = 67 AND subid = 6 ;
UPDATE action_line SET indicator_description = 'Valor do Alcance Orgânico Anual das publicações realizadas por meio do perfil institucional da Prefeitura na Rede Social Facebook.' WHERE id = 68 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de centrais telefônicas incorporadas no período' WHERE id = 69 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Percentual de serviços online' WHERE id = 69 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Percentual de serviços mapeados e redesenhados do total do contrato' WHERE id = 69 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de sistemas de tecnologia da Prefeitura integrados ou absorvidos no SIGRC no período' WHERE id = 69 AND subid = 7 ;
UPDATE action_line SET indicator_description = 'Nº de boletins lançados' WHERE id = 69 AND subid = 8 ;
UPDATE action_line SET indicator_description = 'Índice de Qualidade de Inserção' WHERE id = 69 AND subid = 9 ;
UPDATE action_line SET indicator_description = 'Km de vias pavimentadas/recapeadas' WHERE id = 70 AND subid = 1 ;
UPDATE action_line SET indicator_description = 'Km de vias pavimentadas/recapeadas por meio de parcerias' WHERE id = 70 AND subid = 2 ;
UPDATE action_line SET indicator_description = 'Bases de dados e programação de recapeamento disponibilizadas em formato de dados abertos no GeoSampa e Portal das Transparência' WHERE id = 70 AND subid = 5 ;
UPDATE action_line SET indicator_description = 'Nº de ações concentradas de zeladoria urbana realizadas' WHERE id = 71 AND subid = 4 ;


UPDATE action_line SET achievement = 'Interface com CET que permita comunicação bidirecional de ocorrências no trânsito implantada.' WHERE id = 3 AND subid = 7 ;
UPDATE action_line SET achievement = 'Aplicativo lançado' WHERE id = 4 AND subid = 4 ;
UPDATE action_line SET achievement = 'Lançamento da plataforma de acesso ao agendamento de consultas, exames e procedimentos' WHERE id = 4 AND subid = 5 ;
UPDATE action_line SET achievement = 'Modelo Municipal de Gestão da Qualidade, Humanização e Segurança do Paciente publicado' WHERE id = 5 AND subid = 1 ;
UPDATE action_line SET achievement = 'Diagnóstico de todos os estabelecimentos da Rede Municipal de Saúde da cidade de São Paulorealizado' WHERE id = 5 AND subid = 3 ;
UPDATE action_line SET achievement = 'Decreto publicado' WHERE id = 8 AND subid = 1 ;
UPDATE action_line SET achievement = 'Sala de Gestão da Rede implantada' WHERE id = 8 AND subid = 2 ;
UPDATE action_line SET achievement = 'Protocolo intersecretarial publicado' WHERE id = 8 AND subid = 3 ;
UPDATE action_line SET achievement = 'Protocolo publicado' WHERE id = 8 AND subid = 4 ;
UPDATE action_line SET achievement = 'Protoloco publicado' WHERE id = 8 AND subid = 5 ;
UPDATE action_line SET achievement = 'Ferramenta de cadastro implantada' WHERE id = 8 AND subid = 14 ;
UPDATE action_line SET achievement = 'Unidade instalada' WHERE id = 8 AND subid = 16 ;
UPDATE action_line SET achievement = 'Material educativo publicado' WHERE id = 8 AND subid = 17 ;
UPDATE action_line SET achievement = 'Parceria firmada' WHERE id = 9 AND subid = 5 ;
UPDATE action_line SET achievement = 'Parceria firmada' WHERE id = 9 AND subid = 6 ;
UPDATE action_line SET achievement = 'Parceria firmada' WHERE id = 9 AND subid = 7 ;
UPDATE action_line SET achievement = 'Parceria firmada' WHERE id = 9 AND subid = 8 ;
UPDATE action_line SET achievement = 'Parceria firmada' WHERE id = 9 AND subid = 9 ;
UPDATE action_line SET achievement = 'Protocolo publicado' WHERE id = 9 AND subid = 10 ;
UPDATE action_line SET achievement = 'Guia de serviços publicizada' WHERE id = 10 AND subid = 1 ;
UPDATE action_line SET achievement = 'Equipes constituídas de acordo com cronograma(indicador de monitoramento)' WHERE id = 10 AND subid = 2 ;
UPDATE action_line SET achievement = 'Sistema em funcionamento' WHERE id = 10 AND subid = 5 ;
UPDATE action_line SET achievement = 'Questionário desenvolvido' WHERE id = 10 AND subid = 6 ;
UPDATE action_line SET achievement = 'Aplicativo em funcionamento' WHERE id = 10 AND subid = 8 ;
UPDATE action_line SET achievement = 'Obtenção do selo inicial' WHERE id = 11 AND subid = 1 ;
UPDATE action_line SET achievement = 'Obtenção do selo intermediário' WHERE id = 11 AND subid = 2 ;
UPDATE action_line SET achievement = 'Obtenção do selo final' WHERE id = 11 AND subid = 3 ;
UPDATE action_line SET achievement = 'Pagamento Unificado' WHERE id = 12 AND subid = 2 ;
UPDATE action_line SET achievement = 'Unidades reordenadas conforme diagnóstico' WHERE id = 13 AND subid = 3 ;
UPDATE action_line SET achievement = 'Metodologia criada' WHERE id = 14 AND subid = 4 ;
UPDATE action_line SET achievement = 'Publicação do Indicador de Qualidade doAcolhimento à População em Situação de Rua' WHERE id = 15 AND subid = 3 ;
UPDATE action_line SET achievement = 'Formalização de parceria/integração com a Polícia Estadual' WHERE id = 16 AND subid = 2 ;
UPDATE action_line SET achievement = 'Integração do atendimento da GCM àplataforma 156' WHERE id = 16 AND subid = 4 ;
UPDATE action_line SET achievement = 'Implantação do sistema de decisão inteligente em segurança - “Compstat Paulistano”' WHERE id = 16 AND subid = 5 ;
UPDATE action_line SET achievement = 'Implantação do Centro de Operações Integradas' WHERE id = 16 AND subid = 7 ;
UPDATE action_line SET achievement = 'Estruturação do Núcleo de Monitoramento Aéreo' WHERE id = 16 AND subid = 8 ;
UPDATE action_line SET achievement = 'Novo plano de distribuição de DEACimplementado' WHERE id = 17 AND subid = 2 ;
UPDATE action_line SET achievement = 'Lançamento da campanha' WHERE id = 18 AND subid = 2 ;
UPDATE action_line SET achievement = 'Lançamento do programa SampaCor' WHERE id = 18 AND subid = 4 ;
UPDATE action_line SET achievement = 'Lançamento do aplicativo' WHERE id = 18 AND subid = 9 ;
UPDATE action_line SET achievement = 'Apresentação do calendário reestruturado' WHERE id = 18 AND subid = 10 ;
UPDATE action_line SET achievement = 'Lançamento do plano' WHERE id = 18 AND subid = 11 ;
UPDATE action_line SET achievement = 'Lançamento do programa' WHERE id = 18 AND subid = 12 ;
UPDATE action_line SET achievement = 'MROSC implementado' WHERE id = 19 AND subid = 2 ;
UPDATE action_line SET achievement = 'Instância reguladora implementada' WHERE id = 19 AND subid = 3 ;
UPDATE action_line SET achievement = 'Currículo da Cidade de São Paulo construído' WHERE id = 23 AND subid = 1 ;
UPDATE action_line SET achievement = 'Currículo publicado e divulgado' WHERE id = 23 AND subid = 2 ;
UPDATE action_line SET achievement = 'Formalização do alinhamento ao Currículo da Cidade de São Paulo como pré-requisito para aprovação de propostas de ações de formação' WHERE id = 23 AND subid = 4 ;
UPDATE action_line SET achievement = 'Matriz curricular e itens das avaliações externas alinhados ao currículo construído' WHERE id = 23 AND subid = 5 ;
UPDATE action_line SET achievement = 'Relatório com o perfil dos alunos evadidos ou reprovados por frequência na Rede Municipal de Ensino' WHERE id = 24 AND subid = 1 ;
UPDATE action_line SET achievement = 'Orientação normativa intersecretarial criada e publicada' WHERE id = 24 AND subid = 4 ;
UPDATE action_line SET achievement = 'Formalização de estratégia de articulação de programas e ações de diversos órgãos municipais para prevenção da evasão escolar' WHERE id = 24 AND subid = 5 ;
UPDATE action_line SET achievement = 'Planilhadadas as informações de atividades formativas existentes na SME e DRE. Encontros realizados' WHERE id = 25 AND subid = 1 ;
UPDATE action_line SET achievement = 'Portaria publicada' WHERE id = 25 AND subid = 2 ;
UPDATE action_line SET achievement = 'Normatizações analisadas com apontamentos de modificações' WHERE id = 25 AND subid = 3 ;
UPDATE action_line SET achievement = 'Indicadores construídos' WHERE id = 25 AND subid = 4 ;
UPDATE action_line SET achievement = 'Documento publicado' WHERE id = 25 AND subid = 5 ;
UPDATE action_line SET achievement = 'Portaria publicada e encontros realizados' WHERE id = 25 AND subid = 6 ;
UPDATE action_line SET achievement = 'Lançamento do projeto' WHERE id = 26 AND subid = 1 ;
UPDATE action_line SET achievement = 'Insumos e equipamentos adquiridos: notebooks, dispositivos 2 em 1 (notebook/tablet) e impressoras 3D' WHERE id = 26 AND subid = 3 ;
UPDATE action_line SET achievement = 'Projeto confeccionado' WHERE id = 27 AND subid = 1 ;
UPDATE action_line SET achievement = 'Projetos artísticos/pinturas de espaços públicos entregues à população nas macrorregiões das cidades' WHERE id = 29 AND subid = 4 ;
UPDATE action_line SET achievement = 'Abertura e implementação da Escola do Grafite' WHERE id = 29 AND subid = 5 ;
UPDATE action_line SET achievement = 'Inauguração das Casas de Cultura de Parelheiros e Cidade Ademar' WHERE id = 29 AND subid = 6 ;
UPDATE action_line SET achievement = 'Plano Estratégico de Comunicação para o Programa Biblioteca Viva' WHERE id = 30 AND subid = 9 ;
UPDATE action_line SET achievement = 'Inaugurado o Centro de Cidadania LGBT' WHERE id = 31 AND subid = 1 ;
UPDATE action_line SET achievement = 'Inaugurada a Casa da Mulher Brasileira' WHERE id = 31 AND subid = 4 ;
UPDATE action_line SET achievement = 'Guia do Selo Voluntário Municipal de Direitos Humanos e Diversidade para Empresas publicado.' WHERE id = 32 AND subid = 1 ;
UPDATE action_line SET achievement = 'Diagnóstico realizado' WHERE id = 32 AND subid = 3 ;
UPDATE action_line SET achievement = 'Rede articulada' WHERE id = 32 AND subid = 6 ;
UPDATE action_line SET achievement = 'Relatório publicado' WHERE id = 33 AND subid = 3 ;
UPDATE action_line SET achievement = 'Plano Municipal publicado' WHERE id = 33 AND subid = 6 ;
UPDATE action_line SET achievement = 'Plantios realizados' WHERE id = 33 AND subid = 8 ;
UPDATE action_line SET achievement = 'Relatório de resultados do diagnóstico' WHERE id = 34 AND subid = 1 ;
UPDATE action_line SET achievement = 'Relatório de resultados da avaliação' WHERE id = 34 AND subid = 4 ;
UPDATE action_line SET achievement = 'Implantação do Programa de comunicação e educação ambiental' WHERE id = 34 AND subid = 9 ;
UPDATE action_line SET achievement = 'Interface implementada' WHERE id = 36 AND subid = 5 ;
UPDATE action_line SET achievement = 'Plataforma desenvolvida e implementada' WHERE id = 37 AND subid = 2 ;
UPDATE action_line SET achievement = 'Plataforma desenvolvida e implementada' WHERE id = 37 AND subid = 3 ;
UPDATE action_line SET achievement = 'Mapeamento publicado' WHERE id = 39 AND subid = 3 ;
UPDATE action_line SET achievement = 'Contratos assinados' WHERE id = 41 AND subid = 1 ;
UPDATE action_line SET achievement = 'Mapeamento dos riscos hidrológicos e tecnológicos Publicados' WHERE id = 46 AND subid = 2 ;
UPDATE action_line SET achievement = 'Definição e publicação da relação de áreas prioritárias para a implantação do gerenciamento de riscos' WHERE id = 46 AND subid = 3 ;
UPDATE action_line SET achievement = 'Programa de mobilização e capacitação em percepção de riscos implantado' WHERE id = 46 AND subid = 6 ;
UPDATE action_line SET achievement = 'Conclusão dos projetos para novas obras prioritárias para o controle de cheias.' WHERE id = 47 AND subid = 2 ;
UPDATE action_line SET achievement = 'Implantação de modelos de previsão de inundação em tempo real' WHERE id = 47 AND subid = 6 ;
UPDATE action_line SET achievement = 'Conclusão dos projetos para as intervenções na Bacia do Córrego Anhangabaú' WHERE id = 47 AND subid = 17 ;
UPDATE action_line SET achievement = 'Publicação do manual de eficiência energética e uso racional da água' WHERE id = 48 AND subid = 1 ;
UPDATE action_line SET achievement = 'Implantação do projeto piloto com os dispositivos definidos' WHERE id = 48 AND subid = 2 ;
UPDATE action_line SET achievement = 'Elaboração dos projetos dentro do novo padrão (novas demandas)' WHERE id = 48 AND subid = 4 ;
UPDATE action_line SET achievement = 'Criação do Comitê Intersecretarial e implantação do fluxo de informações entre SMSO e SMPED' WHERE id = 49 AND subid = 5 ;
UPDATE action_line SET achievement = 'Publicação impressa e online divulgada' WHERE id = 49 AND subid = 8 ;
UPDATE action_line SET achievement = 'Operação Urbana Centro revisada' WHERE id = 50 AND subid = 1 ;
UPDATE action_line SET achievement = 'Proposta de Alteração' WHERE id = 51 AND subid = 1 ;
UPDATE action_line SET achievement = 'Proposta de Ajuste dos Processos de Licenciamento' WHERE id = 51 AND subid = 2 ;
UPDATE action_line SET achievement = 'Autuação eletrônica dos processos de aprovação de construções' WHERE id = 51 AND subid = 3 ;
UPDATE action_line SET achievement = 'Plano publicado' WHERE id = 52 AND subid = 2 ;
UPDATE action_line SET achievement = 'Programa implementado' WHERE id = 52 AND subid = 7 ;
UPDATE action_line SET achievement = 'Painel desenvolvido' WHERE id = 52 AND subid = 9 ;
UPDATE action_line SET achievement = 'Programa publicado' WHERE id = 53 AND subid = 3 ;
UPDATE action_line SET achievement = 'Programa municipa de desenvolvimento econômico lançado' WHERE id = 54 AND subid = 2 ;
UPDATE action_line SET achievement = 'Sistema paulistano de incubadoras de empresas criado' WHERE id = 54 AND subid = 3 ;
UPDATE action_line SET achievement = 'Incubadora escola formalmente constituída' WHERE id = 54 AND subid = 5 ;
UPDATE action_line SET achievement = 'Plataforma implantada' WHERE id = 54 AND subid = 7 ;
UPDATE action_line SET achievement = 'Lançamento do sistema' WHERE id = 55 AND subid = 1 ;
UPDATE action_line SET achievement = 'Integração de 2 sistemas' WHERE id = 55 AND subid = 2 ;
UPDATE action_line SET achievement = 'Informações online' WHERE id = 55 AND subid = 6 ;
UPDATE action_line SET achievement = 'Lançamento do normativo' WHERE id = 55 AND subid = 8 ;
UPDATE action_line SET achievement = 'Publicar indicador regional sobre empreendedorismo' WHERE id = 55 AND subid = 11 ;
UPDATE action_line SET achievement = 'Implementação de sistema automático de liberação do CCM' WHERE id = 55 AND subid = 12 ;
UPDATE action_line SET achievement = 'Sistema implantado' WHERE id = 55 AND subid = 13 ;
UPDATE action_line SET achievement = 'Lançamento do documento' WHERE id = 56 AND subid = 1 ;
UPDATE action_line SET achievement = 'Implantação da unidade móvel' WHERE id = 56 AND subid = 2 ;
UPDATE action_line SET achievement = 'Inclusão do atendimento presencial na Política de Atendimento' WHERE id = 56 AND subid = 4 ;
UPDATE action_line SET achievement = 'Lançamento da plataforma de controle gerencial' WHERE id = 58 AND subid = 3 ;
UPDATE action_line SET achievement = 'Elaboração do Plano Municipal de Desestatização' WHERE id = 59 AND subid = 1 ;
UPDATE action_line SET achievement = 'Realização da primeira reunião ordinária do CMDP' WHERE id = 59 AND subid = 2 ;
UPDATE action_line SET achievement = 'Criação do Fundo Municipal de Desenvolvimento Social' WHERE id = 59 AND subid = 3 ;
UPDATE action_line SET achievement = 'Mapeamento de demandas realizado.' WHERE id = 60 AND subid = 1 ;
UPDATE action_line SET achievement = 'Manual de procedimentos entregue.' WHERE id = 60 AND subid = 2 ;
UPDATE action_line SET achievement = 'Marca criada' WHERE id = 60 AND subid = 7 ;
UPDATE action_line SET achievement = 'Marca licenciada' WHERE id = 60 AND subid = 9 ;
UPDATE action_line SET achievement = 'Publicação do Plano de Redução das Obrigações Acessórias e do Custo de Conformidade dos Contribuintes Paulistanos' WHERE id = 61 AND subid = 2 ;
UPDATE action_line SET achievement = 'Publicização da reformulação do Programa Nota Fiscal Paulistana' WHERE id = 61 AND subid = 3 ;
UPDATE action_line SET achievement = 'Apresentação do plano de reestruturação de precatórios judiciais.' WHERE id = 62 AND subid = 1 ;
UPDATE action_line SET achievement = 'Implantação do Sistema de Bens Imóveis.' WHERE id = 62 AND subid = 2 ;
UPDATE action_line SET achievement = 'Mudança no Serviço Instituída' WHERE id = 63 AND subid = 2 ;
UPDATE action_line SET achievement = 'Entrega de estudos de limpeza e vigilância' WHERE id = 63 AND subid = 3 ;
UPDATE action_line SET achievement = 'Migração do Diário Oficial para o formato eletrônico' WHERE id = 63 AND subid = 6 ;
UPDATE action_line SET achievement = 'Revisão da Tabela de Temporalidade' WHERE id = 63 AND subid = 7 ;
UPDATE action_line SET achievement = 'Sistema Instituído' WHERE id = 63 AND subid = 8 ;
UPDATE action_line SET achievement = 'Sistema da Dívida Ativa integrado às demais plataformas' WHERE id = 64 AND subid = 1 ;
UPDATE action_line SET achievement = 'Núcleo de atuação integrada para o combate à sonegação fiscal implantado' WHERE id = 64 AND subid = 2 ;
UPDATE action_line SET achievement = 'Sistema de Ações Judiciais integrado ao Sistema do Tribunal de Justiça de São Paulo' WHERE id = 64 AND subid = 3 ;
UPDATE action_line SET achievement = 'Sistema de Execuções Fiscais Digitais com intrumentos gerenciais implantados' WHERE id = 64 AND subid = 4 ;
UPDATE action_line SET achievement = 'Edital de Governo Aberto lançado' WHERE id = 65 AND subid = 3 ;
UPDATE action_line SET achievement = 'Plano de comunicação implementado' WHERE id = 65 AND subid = 5 ;
UPDATE action_line SET achievement = 'Rede de servidores do Governo Aberto instituída' WHERE id = 65 AND subid = 6 ;
UPDATE action_line SET achievement = 'Espaço de Coworking criado' WHERE id = 65 AND subid = 7 ;
UPDATE action_line SET achievement = 'Publicação de Decreto Municipal de Transparencia e Dados Abertos' WHERE id = 65 AND subid = 10 ;
UPDATE action_line SET achievement = 'Publicação dos critérios de acessibilidade digitale instrumento de avaliação' WHERE id = 66 AND subid = 1 ;
UPDATE action_line SET achievement = 'Publicação do canal virtual interativo' WHERE id = 66 AND subid = 3 ;
UPDATE action_line SET achievement = 'Publicação da cartilha impressa e virtual' WHERE id = 66 AND subid = 4 ;
UPDATE action_line SET achievement = 'Reestruturação do site piloto' WHERE id = 66 AND subid = 5 ;
UPDATE action_line SET achievement = 'Sistema de monitoramento de obras implementado' WHERE id = 67 AND subid = 3 ;
UPDATE action_line SET achievement = 'Publicação de Decreto Municipal regulamentando das Unidades de Controle Interno' WHERE id = 67 AND subid = 5 ;
UPDATE action_line SET achievement = 'Publicação de Portaria de Regulamentação das Ouvidorias Setoriais' WHERE id = 67 AND subid = 7 ;
UPDATE action_line SET achievement = 'Realização da consulta pública' WHERE id = 68 AND subid = 1 ;
UPDATE action_line SET achievement = 'Realização da hackatona ou café hacker' WHERE id = 68 AND subid = 2 ;
UPDATE action_line SET achievement = 'Plano de comunicação publicado' WHERE id = 68 AND subid = 3 ;
UPDATE action_line SET achievement = 'Portal reestruturado e integrado' WHERE id = 68 AND subid = 4 ;
UPDATE action_line SET achievement = 'Implantação do atendimento do SP 156 via facebook e twitter' WHERE id = 69 AND subid = 3 ;
UPDATE action_line SET achievement = 'Lançamento da Política de Atendimento' WHERE id = 69 AND subid = 4 ;
UPDATE action_line SET achievement = 'Lançamento do aplicativo' WHERE id = 69 AND subid = 6 ;
UPDATE action_line SET achievement = 'Banco de dados geográfico organizado com informações sobre as condições do pavimento do viário municipal' WHERE id = 70 AND subid = 3 ;
UPDATE action_line SET achievement = 'Programa de Recapeamento de Longo Prazo publicado' WHERE id = 70 AND subid = 4 ;
UPDATE action_line SET achievement = 'Eixos e marcos estratégicos definidos' WHERE id = 71 AND subid = 1 ;
UPDATE action_line SET achievement = 'Metodologia para realização das ações de zeladoria do Cidade Linda desenvolvida' WHERE id = 71 AND subid = 2 ;
UPDATE action_line SET achievement = 'Plano de comunicação desenvolvido' WHERE id = 71 AND subid = 3 ;

COMMIT;
